### PR TITLE
Packaging changes

### PR DESCRIPTION
**Pull request by dlech**
These are some changes I make to make packaging easier and get rid of a lintian warning.

### CODE REVIEW

**Comment by ensonic** [comment]
How do I build such a package? I never managed to build a package straight from git :/

**Comment by dlech** [comment]
You should be able to just run `debuild` in the source code directory. Add the `-us -uc` options if you don't have a gpg key setup for signing. Then `debuild clean` to clean up the mess.

**Comment by dlech** [comment]
rebased.

**Comment by ensonic** [comment]
Thanks!

**Pull request merged**
